
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bus_user
      POSTGRES_PASSWORD: bus_password
      POSTGRES_DB: bus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://bus_user:bus_password@db:5432/bus_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro

  scheduler:
    build: ./data_ingestion
    environment:
      DB_HOST: db
      DB_NAME: bus_db
      DB_USER: bus_user
      DB_PASSWORD: bus_password
    depends_on:
      - db
    # For nightly updates
    command: bash -c "echo '0 3 * * * python /app/ingest_timetables.py' | crontab - && cron -f"

volumes:
  postgres_data:
